# Generated by Django 5.0.2 on 2024-02-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_handling', '0002_remove_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test_cases',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
